-- GENERATED FILE -- do not hand-edit.
-- Regenerate with `conquer3 db gen-gold-ddl` after changing core/schema.py's
-- FEATURE_NAMES, pg_column_type(), or EXTERNAL_MODEL_FEATURES, then commit the
-- result (bump FEATURE_SCHEMA_VERSION too if FEATURE_NAMES changed).
-- tests/unit/test_ddl_gen.py enforces this file stays in sync.
--
-- Feature columns are nullable: conquer3.core.features leaves window features
-- undefined (NULL) on an account's first transaction -- see COLD_START_NULL_FEATURES
-- in core/schema.py.
CREATE TABLE IF NOT EXISTS gold.txn_features (
    event_id                 TEXT NOT NULL PRIMARY KEY,
    account_id                TEXT NOT NULL,
    event_ts_us                BIGINT NOT NULL,
    feature_schema_version     INTEGER NOT NULL,
    is_first_txn                double precision,
    seconds_since_last_txn      double precision,
    log1p_seconds_since_last    double precision,
    steps_since_last_txn        double precision,
    amount                      double precision,
    log1p_amount                double precision,
    amount_delta_vs_last        double precision,
    amount_ratio_vs_last        double precision,
    amount_velocity             double precision,
    amount_ratio_vs_prior_mean  double precision,
    amount_ratio_vs_prior_max   double precision,
    amount_z_vs_prior           double precision,
    txn_count_prior             double precision,
    account_age_hours           double precision,
    txn_rate_per_hour           double precision,
    type_changed                double precision,
    is_fraud_capable_type       double precision,
    balance_gap_org             double precision,
    balance_gap_flag            double precision,
    error_balance_orig          double precision,
    error_balance_dest          double precision,
    balance_delta_org           double precision,
    amount_to_balance_ratio     double precision,
    drains_account              double precision,
    orig_balance_was_zero       double precision,
    dest_is_merchant            double precision,
    dest_is_new                 double precision,
    dest_balance_was_zero       double precision,
    hour_of_day                 double precision,
    sim_day_of_week             double precision,
    prev_fraud_score            double precision,
    txn_type                    text,
    prev_txn_type               text,
    type_pair                   text,
    --
    -- Below: reserved for other MLflow-registered models' own feature names (see
    -- core/schema.py's EXTERNAL_MODEL_FEATURES). conquer3.core.features never
    -- computes these and the champion scorer never reads them -- always NULL until
    -- a job backfills that specific model's features.
    amount_log                  double precision,
    amount_log10                double precision,
    amount_log_zscore_by_type_hour double precision,
    amount_ratio                double precision,
    amount_to_dest_mean_ratio   double precision,
    amount_to_orig_mean_ratio   double precision,
    amount_zscore_by_type_hour  double precision,
    current_amount              double precision,
    day_index                   integer,
    day_of_week                 integer,
    dest_amount_mean            double precision,
    dest_amount_mean_hist       double precision,
    dest_amount_sum_hist        double precision,
    dest_cashout_freq           integer,
    dest_count_hist             bigint,
    dest_freq                   integer,
    dest_is_frequent            integer,
    dest_risk_target_enc        double precision,
    dest_type_count             integer,
    dest_velocity_1h            integer,
    dest_velocity_24h           integer,
    dest_velocity_surge_ratio   double precision,
    edge_count_hist             bigint,
    edge_is_new                 integer,
    f1                          double precision,
    f2                          double precision,
    f3                          double precision,
    hour_cos                    double precision,
    hour_day                    integer,
    hour_sin                    double precision,
    is_capped_10m               integer,
    is_customer_dest            integer,
    is_mule_chain               integer,
    is_night                    integer,
    is_rapid_passthrough        integer,
    is_round_10k                integer,
    is_round_1k                 integer,
    is_transfer                 integer,
    is_weekend                  integer,
    log_amount                  double precision,
    mule_time_since_transfer    double precision,
    orig_amount_mean_hist       double precision,
    orig_amount_sum_hist        double precision,
    orig_count_hist             bigint,
    orig_is_first_seen          integer,
    orig_velocity_1h            integer,
    orig_velocity_24h           integer,
    pit_distinct_senders_168h   double precision,
    pit_distinct_senders_24h    double precision,
    pit_prior_amount_168h       double precision,
    pit_prior_amount_1h         double precision,
    pit_prior_amount_24h        double precision,
    pit_prior_count_1h          double precision,
    pit_prior_count_24h         double precision,
    pit_steps_since_last_event  double precision,
    step                        bigint,
    step_day                    integer,
    transaction_type_transfer   double precision,
    type                        text,
    type_code                   integer,
    is_fraud                   BOOLEAN NOT NULL,
    is_flagged_fraud           BOOLEAN NOT NULL
);
